name: Build And Test

on:
    pull_request:
      branches:
        - main
      types: [synchronize, opened, reopened, ready_for_review]


jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: nvcr.io/nvidia/tritonserver:25.06-py3
      volumes:
        - ${{ github.workspace }}:/core
        # Mount /usr so we can free space
        - /usr:/host_usr
      env:
        AGENT_TOOLSDIRECTORY: "$AGENT_TOOLSDIRECTORY"
        CMAKE_POLICY_VERSION_MINIMUM: 3.5

    steps:
      - uses: actions/checkout@v3

      - name: "prepare: free space"
        run: |
          rm -rf \
            /host_usr/share/dotnet /host_usr/local/lib/android /opt/ghc \
            /host_usr/local/share/powershell /host_usr/share/swift /host_usr/local/.ghcup \
            /host_usr/lib/jvm
          rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: "dependencies: apt"
        run: |
          apt update -qq && \
          apt install -y --no-install-recommends \
            clang-format-15 \
            libb64-dev \
            libre2-dev \
            rapidjson-dev
      - name: "dependencies: pip"
        run: |
          pip install \
            cmake==4.0.3 \
            build \
            pytest \
            pytest-asyncio
      - name: "dependencies: boost"
        run: |
          wget -O /tmp/boost.tar.gz https://archives.boost.io/release/1.80.0/source/boost_1_80_0.tar.gz && \
          tar xzf /tmp/boost.tar.gz -C /tmp && \
          mv /tmp/boost_1_80_0/boost /usr/include/boost && \
          rm /tmp/boost.tar.gz

      - name: "build: cmake"
        run: |
          cmake \
            -DCMAKE_INSTALL_PREFIX:PATH=/core/install \
            -DTRITON_CORE_HEADERS_ONLY=OFF \
            -S /core \
            -B /core/build
          cmake --build /core/build --parallel 8 -v
        working-directory: /core

      - name: "test: pytest"
        run: |
          python3 -m pip install --force-reinstall /core/build/python/generic/wheel/dist/tritonserver-*.whl
          pytest /core/python/test -v
